### PR TITLE
add custom loading template

### PR DESCRIPTION
**Pull request by wykhuh**
@pigstake I added a custom loading template. Can you change the text and css?

### CODE REVIEW

**Comment by pigstake** [comment]
@wykhuh It looks like the loader package I installed doesn't work on this branch. If you checkout master, switch between creating a new board and going back to the board creation form. Notice on the top of the view there is a gradient progress bar. On this branch, that bar does not show up for me. Do you think they conflict?

**Comment by pigstake** [comment]
@wykhuh Also, where does the loading template get injected? Can I, say, put a little spinner in there and render the template inside another template like any other module?

**Comment by wykhuh** [comment]
@pigstake I still see the spinner. If you start the server, visit localhost:3000, the stop the server, and create a new board, you should loading page and spinner.

**Comment by pigstake** [comment]
@wykhuh Got it. I updated the loading module. Good to go on my end.

**Comment by pigstake** [comment]
@wykhuh If this is ready to merge on your end, then :shipit: :sheep: :rocket:

**Pull request merged**
