### PR TITLE
Feature/add timer

### PR DESCRIPTION
**Pull request by wykhuh**
@mikehmorrissey  @pigstake  added a timer. Need help with UX and styling. This is my first meteor project, so the code might not look meteor-like.

screen shot 2015-09-12 at 7 43 10 pm

### CODE REVIEW

**Comment by taboularasa** [comment]
:+1:

**Comment by pigstake** [comment]
@wykhuh Awesome! I'm ooo today and tomorrow. Ill check this out when i get back and share the trello release backlog. Were putting feature requests into a backlog that gets prioritized, designed and tested before release. So when we move the timer feature into a current release, lets talk about this in more depth. I'd love to have your help on current release stories. There's some interesting engineering work to be done asap!

**Comment by pigstake** [comment]
Nice work! Holding off on this until we prioritize this feature into a release, though.

**Comment by wykhuh** [comment]
Close pull request until the next sprint.

**Pull request closed without merging**
