### PR TITLE
included fourseven meteor-scss to use SCSS and Scut for utility classes

### PR DESCRIPTION
**Pull request by pigstake**
@nrswolf

### CODE REVIEW

**Comment by mikehmorrissey** [comment]
@pigstake add bower_components to the .gitignore. They will get generated when the bower command is called. Looks good besides that. The fourseven package is great. Been flawless for me so far.

**Comment by pigstake** [comment]
@mikehmorrissey I considered it, but figured I'd let Russell handle that if need be. After reading your comment, I decided to just do it. Then I found this: http://stackoverflow.com/questions/22327758/should-bower-components-be-gitignored

Thoughts?

**Comment by mikehmorrissey** [comment]
@pigstake ah interesting. That actually makes sense. I wonder if bower is part of the meteor build process. If so I think it should be left out otherwise included.  Did you run bower separately is it a meteor package?

**Comment by pigstake** [comment]
@mikehmorrissey hmm, not sure. I have Bower installed on my computer via NPM. I used Bower to install Scut. But I understand what you're saying; I just don't know how to answer for sure.

**Comment by mikehmorrissey** [comment]
@pigstake okay cool. I say :shipit: as is

**Pull request merged**
