### PR TITLE
installed meteorhacks:npm package and kss:node npm module

### PR DESCRIPTION
**Pull request by pigstake**
@wykhuh Here's the kss-node integration branch.

@mikehmorrissey Take a look if you're interested. I wimped out and used meteorhacks:npm. It's broken, though, so wrapping it ourselves might a step towards a solution. *shrug*

### CODE REVIEW

**Comment by pigstake** [comment]
Shit I probably shouldn't have added the npm modules. I'll roll back and push again.

**Comment by pigstake** [comment]
@wykhuh @mikehmorrissey When you get a chance, advise me about including the package files in this commit. If I should keep them included, I won't waste my time trying to un-include them.

**Comment by wykhuh** [comment]
@pigstake cleaned up the branch. To run kss, you need to use this in the command line
`packages/npm-container/.npm/package/node_modules/.bin/kss-node --source client/assets/app/stylesheets --destination packages/styleguide `

`packages/npm-container/.npm/package/node_modules/.bin/kss-node` is the location of the kss binary

`--source client/assets/app/stylesheets` is the folder containing the style sheets

`client/assets/app/stylesheets --destination packages/styleguide ` is the folder for the styleguide. I stuck the styleguide inside packages, because if you put the styleguide anywhere else inside the dot-votr, Meteor will try to process the files. You could also put the styleguide outside dot-votr.

**Comment by pigstake** [comment]
@wykhuh Awesome. I'll wrap my brain around this when I have time for Dotvoter :smile: If you think it's merge-able, you can merge it. Or @mikehmorrissey

**Comment by wykhuh** [comment]
@pigstake I merged the kss branch. I also added a page to the project wiki about how to run kss.

**Pull request merged**
